"""Generate a self-contained C99 state estimator from a Python cell model.

This is the part of :mod:`cellkernel` that does something the rest of the
open-source battery ecosystem does not. PyBaMM simulates, PyBOP identifies
parameters, and both are excellent at it -- but both stop at the Python boundary.
Getting a physics-based estimator onto the microcontroller that actually runs a
battery pack is left as an exercise, and in practice it is done by hand, in C, by
someone translating equations from a paper. That translation is where the errors
go in, and it is unverifiable after the fact.

Here the translation is mechanical and the result is checked. One call produces a
buildable C library plus a report:

>>> from cellkernel.codegen import generate
>>> from cellkernel.models import SPM
>>> from cellkernel.params import chen2020_nmc811_graphite
>>> model = SPM(chen2020_nmc811_graphite(), dt=1.0, rom="pade", order=3)
>>> result = generate(model, "build/estimator", precision="float")

What is emitted
---------------
``cellkernel_estimator.h``, ``cellkernel_estimator.c``
    The estimator. No dynamic allocation, no global mutable state, fixed-size
    arrays, bounded execution time.
``ck_harness.c``
    A host harness that replays a CSV, used for verification and as a worked
    example of the call sequence.
``Makefile``, ``CMakeLists.txt``
    Enough build glue to compile the harness on a host.
``BUDGET.txt``
    Flash, RAM, stack, operation counts and a cycle estimate.

Verifying it
------------
Generating code is only half the claim. :mod:`cellkernel.verify` compiles the
result, replays the same current profile through the compiled binary and through
a Python mirror of it, and reports the divergence -- separating code-generation
error from the approximations the generated code makes on purpose.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from .budget import ResourceBudget, estimate_budget
from .emit import emit_header, emit_main, emit_source
from .spec import EstimatorSpec, ReferenceEstimator, spec_from_spm, table_backed_model

__all__ = [
    "EstimatorSpec",
    "GeneratedProject",
    "ReferenceEstimator",
    "ResourceBudget",
    "estimate_budget",
    "generate",
    "spec_from_spm",
    "table_backed_model",
]

_MAKEFILE = """\
# Generated by cellkernel. Builds the host verification harness.
CC      ?= cc
CFLAGS  ?= -std=c99 -O2 -Wall -Wextra -Wpedantic -Werror
LDLIBS  ?= -lm

ck_harness: ck_harness.c cellkernel_estimator.c cellkernel_estimator.h
\t$(CC) $(CFLAGS) -o $@ ck_harness.c cellkernel_estimator.c $(LDLIBS)

.PHONY: clean
clean:
\trm -f ck_harness ck_harness.exe
"""

_CMAKE = """\
# Generated by cellkernel.
cmake_minimum_required(VERSION 3.15)
project(cellkernel_estimator C)

set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)

add_library(cellkernel_estimator STATIC cellkernel_estimator.c)
target_include_directories(cellkernel_estimator PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})

add_executable(ck_harness ck_harness.c)
target_link_libraries(ck_harness PRIVATE cellkernel_estimator m)
"""


@dataclass(frozen=True)
class GeneratedProject:
    """Where the generated sources went, and what they cost."""

    directory: Path
    spec: EstimatorSpec
    budget: ResourceBudget
    precision: str
    files: tuple[str, ...]

    def reference(self) -> ReferenceEstimator:
        """A NumPy mirror of the emitted code, for cross-checking."""
        return ReferenceEstimator(self.spec)

    def __str__(self) -> str:
        return (
            f"generated {self.spec.n_states}-state {self.precision} estimator in "
            f"{self.directory} ({', '.join(self.files)})"
        )


def generate(
    model,
    directory: str | Path,
    precision: str = "double",
    table_points: int = 257,
    measurement_noise: float = 1e-4,
    process_noise=None,
    initial_soc_uncertainty: float = 0.05,
    max_c_rate: float = 3.0,
    overwrite: bool = True,
) -> GeneratedProject:
    """Emit a buildable C estimator for ``model``.

    Parameters
    ----------
    model
        A constructed :class:`~cellkernel.models.spm.SPM`.
    directory
        Output directory, created if absent.
    precision
        ``"float"`` or ``"double"``. Use ``"float"`` for a target with a
        single-precision FPU: the covariance propagation is the bulk of the work
        and it runs roughly fifteen times faster. The verification harness will
        tell you what that costs in accuracy -- typically a few tens of
        microvolts, which is far below the measurement noise of any real front
        end.
    table_points
        Samples per open-circuit-potential table.
    measurement_noise
        Voltage measurement variance, V^2.
    process_noise
        Diagonal of the process noise covariance. Defaults to a heuristic based on
        a 0.2% per-step current-integration error.
    initial_soc_uncertainty
        Standard deviation of the initial state of charge estimate.
    max_c_rate
        Largest C-rate the estimator must remain valid at. Sets how far the
        open-circuit-potential tables extend beyond the bulk stoichiometry window
        to cover surface excursion under load. See
        :func:`cellkernel.codegen.spec.table_domain`.
    overwrite
        Whether to replace an existing directory.
    """
    if precision not in {"float", "double"}:
        raise ValueError("precision must be 'float' or 'double'")

    spec = spec_from_spm(
        model,
        table_points=table_points,
        process_noise=process_noise,
        measurement_noise=measurement_noise,
        initial_soc_uncertainty=initial_soc_uncertainty,
        max_c_rate=max_c_rate,
    )
    budget = estimate_budget(spec, precision)

    out = Path(directory)
    if out.exists() and overwrite:
        shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)

    payload = {
        "cellkernel_estimator.h": emit_header(spec, precision),
        "cellkernel_estimator.c": emit_source(spec, precision),
        "ck_harness.c": emit_main(spec),
        "Makefile": _MAKEFILE,
        "CMakeLists.txt": _CMAKE,
        "BUDGET.txt": budget.summary() + "\n",
    }
    for filename, text in payload.items():
        (out / filename).write_text(text, encoding="utf-8", newline="\n")

    return GeneratedProject(
        directory=out,
        spec=spec,
        budget=budget,
        precision=precision,
        files=tuple(payload),
    )
